### ISSUE TITLE
Some Errors in EAEF-RGBT-CC

### ISSUE THREAD

**Issue by ZhaZhahe** [FreeformRobotics/EAEFNet#11]
when i run the "EAEF_CC/test.py", it occur following RuntimeError. i guess there are some mistakes in the Trained Model of best_model_29.pth
Traceback (most recent call last):
  File "/home/zhanghan/workspace/EAEFNet/EAEFNet_RGBT-CC/EAEF_CC/test.py", line 30, in <module>
    model.load_state_dict(checkpoint)
  File "/home/zhanghan/software/miniconda3/envs/EAEF/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for FusionModel:
	Unexpected key(s) in state_dict: "block1.rgb_msc.conv.0.weight",......

**Comment by matrixgame2018** [comment]
OK， thx， I will check for these mistakes and fix them soon.
